### ISSUE TITLE
Special characters with password

### ISSUE THREAD

**Issue by huayueh** [sujrd/dbpinger#5]
I'm not familiar with Go so all I can try out is hard code account/password in source code and it works fine but if it comes from conf file it will fail.

**Comment by hsanson** [comment]
Exactly what special characters are you using? I wrote a test using passwords with &, %, $, etc and they all worked. Unless you have " or ' in your password then it should work.

**Comment by huayueh** [comment]
Hi this is what include in our password
!, #, -, @

**Comment by hsanson** [comment]
The # is considered a comment in the conf file so if you have a password like "123#45" it will be read as "123" with everything after the # being ignored.

If you need a # in your configuration you must put all between "":

```
dbpass="my#password"
```

**Comment by huayueh** [comment]
Got it. I suggest using "" in the conf file of readme to prevent this kind of situation for other user
dbuser = "<user>"     # Cluster node username.
dbpass = "<pass>"     # Cluster node password.
